<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="D:\framework\test\nunit\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll" total="4" errors="0" failures="2" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2020-03-17" time="09:56:36">
  <environment nunit-version="3.6.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.18363.0" platform="Win32NT" cwd="D:\framework\test\nunit\UnitTestProject1\UnitTestProject1\bin\Debug" machine-name="KNYSHS" user="s.knysh" user-domain="ITRANSITION" />
  <culture-info current-culture="ru-RU" current-uiculture="en-US" />
  <test-suite type="Assembly" name="D:\framework\test\nunit\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll" executed="True" result="Failure" success="False" time="0.086" asserts="0">
    <properties>
      <property name="_PID" value="21528" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
      <stack-trace />
    </failure>
    <results>
      <test-suite type="Namespace" name="UnitTestProject1" executed="True" result="Failure" success="False" time="0.079" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
          <stack-trace />
        </failure>
        <results>
          <test-suite type="TestFixture" name="UnitTest1" executed="True" result="Failure" success="False" time="0.059" asserts="0">
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
              <stack-trace />
            </failure>
            <results>
              <test-case name="UnitTestProject1.UnitTest1.TestMethod1" executed="True" result="Success" success="True" time="0.018" asserts="0" />
              <test-case name="UnitTestProject1.UnitTest1.TestMethod2" executed="True" result="Failure" success="False" time="0.032" asserts="0">
                <failure>
                  <message><![CDATA[TestMethod2]]></message>
                  <stack-trace><![CDATA[   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at UnitTestProject1.UnitTest1.TestMethod2() in D:\framework\test\nunit\UnitTestProject1\UnitTestProject1\UnitTest1.cs:line 19]]></stack-trace>
                </failure>
              </test-case>
            </results>
          </test-suite>
          <test-suite type="TestFixture" name="UnitTest2" executed="True" result="Failure" success="False" time="0.017" asserts="0">
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
              <stack-trace />
            </failure>
            <results>
              <test-case name="UnitTestProject1.UnitTest2.TestMethod3" executed="True" result="Success" success="True" time="0.010" asserts="0" />
              <test-case name="UnitTestProject1.UnitTest2.TestMethod4" executed="True" result="Failure" success="False" time="0.006" asserts="0">
                <failure>
                  <message><![CDATA[TestMethod2]]></message>
                  <stack-trace><![CDATA[   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at UnitTestProject1.UnitTest2.TestMethod4() in D:\framework\test\nunit\UnitTestProject1\UnitTestProject1\UnitTest2.cs:line 19]]></stack-trace>
                </failure>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>